version: '3.9'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "account"
    ports:
      - "5432:5432"